basePath: /
consumes:
- application/json
info:
  description: Documentation for Product API
  title: Product API.
  version: 1.0.0
paths: {}
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
